#!/bin/bash
set -e

cd /root/.openclaw

OPENCLAW_CONFIG="/root/.openclaw/.openclaw/openclaw.json"

# ===========================================================
# 1-4. SETUP (runs if openclaw.json is missing)
# ===========================================================
if [ ! -f "$OPENCLAW_CONFIG" ]; then
  echo "[entrypoint] First run — configuring..."

  # 1. Generate openclaw.json from env vars + auto-detect Discord guilds
  echo "[entrypoint] Generating OpenClaw config..."
  node docker/generate-openclaw-config.js

  # 2. Register agents
  echo "[entrypoint] Registering agents..."
  bash docker/setup-agents.sh

  # 3. Inject env vars into .md files
  bash docker/inject-env-vars.sh

  # 4. Link cron jobs to where OpenClaw expects them
  mkdir -p .openclaw/cron
  if [ -f cron/jobs.json ] && [ ! -f .openclaw/cron/jobs.json ]; then
    ln -sf /root/.openclaw/cron/jobs.json .openclaw/cron/jobs.json
    echo "[entrypoint] Linked cron jobs ($(python3 -c "import json; print(len(json.load(open('cron/jobs.json')).get('jobs',[])))" 2>/dev/null || echo '?') jobs)"
  fi

  echo "[entrypoint] Setup complete."
else
  echo "[entrypoint] Config exists, skipping setup."
fi

# ===========================================================
# 1b. ENSURE MC-CHAT PLUGIN (runs every startup)
# ===========================================================
MC_CHAT_PLUGIN="/root/.openclaw/plugins/mc-chat"
if [ -d "$MC_CHAT_PLUGIN" ]; then
  # Check if plugin is registered in config
  if ! python3 -c "import json; c=json.load(open('$OPENCLAW_CONFIG')); assert 'mc-chat' in c.get('plugins',{}).get('entries',{})" 2>/dev/null; then
    echo "[entrypoint] Registering mc-chat plugin..."
    openclaw plugins install --link "$MC_CHAT_PLUGIN" 2>/dev/null || true
  fi
  # Ensure channel config and binding exist
  python3 -c "
import json, sys
f='$OPENCLAW_CONFIG'
c=json.load(open(f))
changed=False
if 'mc-chat' not in c.get('channels',{}):
    c.setdefault('channels',{})['mc-chat']={'enabled':True,'mcServerUrl':'http://localhost:18790'}
    changed=True
if not any(b.get('match',{}).get('channel')=='mc-chat' for b in c.get('bindings',[])):
    c.setdefault('bindings',[]).append({'agentId':'sancho','match':{'channel':'mc-chat'}})
    changed=True
if changed:
    json.dump(c, open(f,'w'), indent=2)
    print('[entrypoint] mc-chat channel config + binding added')
" 2>/dev/null || true
fi

# ===========================================================
# 4. NODE DEPENDENCIES (ws for MC server)
# ===========================================================
if [ -f workspace-sancho/package.json ] && [ ! -d workspace-sancho/node_modules ]; then
  echo "[entrypoint] Installing Node dependencies..."
  (cd workspace-sancho && npm install --production --quiet)
fi

# ===========================================================
# 5. GENERATE MC DASHBOARD DATA (if missing)
# ===========================================================
if [ ! -f workspace-sancho/mission-control.html ] || [ ! -f workspace-sancho/memory/mc/agents-data.js ]; then
  echo "[entrypoint] Generating dashboard data..."
  (cd workspace-sancho && python3 scripts/regenerate.py 2>/dev/null) || \
    echo "[entrypoint] WARNING: regenerate.py failed (dashboard data will be generated by cron)"
fi

# ===========================================================
# 6. START GATEWAY (foreground, backgrounded for MC)
# ===========================================================
echo "[entrypoint] Starting OpenClaw gateway..."
openclaw gateway run &
GATEWAY_PID=$!

echo "[entrypoint] Waiting for gateway on :18789..."
TRIES=0
until curl -sf http://localhost:18789/healthz > /dev/null 2>&1; do
  TRIES=$((TRIES + 1))
  if [ $TRIES -ge 30 ]; then
    echo "[entrypoint] ERROR: Gateway did not start after 60s"
    exit 1
  fi
  sleep 2
done
echo "[entrypoint] Gateway ready (PID $GATEWAY_PID)."

# ===========================================================
# 7. START MC SERVER
# ===========================================================
echo "[entrypoint] Starting Mission Control on :18790..."
node workspace-sancho/scripts/mc-server.js &
MC_PID=$!

echo "[entrypoint] All services running. Gateway=$GATEWAY_PID MC=$MC_PID"

# ===========================================================
# 8. WAIT — if either process dies, container stops
# ===========================================================
wait -n $GATEWAY_PID $MC_PID
EXIT_CODE=$?
echo "[entrypoint] A process exited with code $EXIT_CODE. Shutting down."
kill $GATEWAY_PID $MC_PID 2>/dev/null
exit $EXIT_CODE
