#!/bin/bash
set -e

cd /root/.openclaw

# ===========================================================
# 1. GENERATE OPENCLAW CONFIG
#    Auto-detects Discord guilds, registers agents, creates
#    bindings. Idempotent — merges with existing config.
# ===========================================================
echo "[entrypoint] Configuring OpenClaw..."
node docker/generate-openclaw-config.js

# ===========================================================
# 2. REGISTER AGENTS (if not already registered)
#    Uses openclaw agents add CLI for proper registration.
# ===========================================================
AGENT_COUNT=$(openclaw agents list --json 2>/dev/null | python3 -c "
import json,sys
try:
    d=json.load(sys.stdin)
    print(len([a for a in d.get('agents',[]) if a.get('name') != 'main']))
except:
    print('0')
" 2>/dev/null || echo "0")

if [ "$AGENT_COUNT" -lt 4 ]; then
  echo "[entrypoint] Registering agents..."
  bash docker/setup-agents.sh
fi

# ===========================================================
# 3. ENV VAR INJECTION INTO .md FILES
#    Replace {UPPER_SNAKE_CASE} placeholders with env values.
#    Allows SOUL.md, TOOLS.md etc. to reference MC_BASE_URL,
#    CERVANTES_GUILD_ID, etc. without hardcoding.
# ===========================================================
bash docker/inject-env-vars.sh

# ===========================================================
# 4. NODE DEPENDENCIES (ws for MC server)
# ===========================================================
if [ -f workspace-sancho/package.json ] && [ ! -d workspace-sancho/node_modules ]; then
  echo "[entrypoint] Installing Node dependencies..."
  (cd workspace-sancho && npm install --production --quiet)
fi

# ===========================================================
# 5. GENERATE MC DASHBOARD DATA (if missing)
# ===========================================================
if [ ! -f workspace-sancho/mission-control.html ] || [ ! -f workspace-sancho/agents-data.js ]; then
  echo "[entrypoint] Generating dashboard data..."
  (cd workspace-sancho && python3 scripts/regenerate.py 2>/dev/null) || \
    echo "[entrypoint] WARNING: regenerate.py failed (dashboard data will be generated by cron)"
fi

# ===========================================================
# 6. START GATEWAY (foreground, backgrounded for MC)
# ===========================================================
echo "[entrypoint] Starting OpenClaw gateway..."
openclaw gateway run &
GATEWAY_PID=$!

echo "[entrypoint] Waiting for gateway on :18789..."
TRIES=0
until curl -sf http://localhost:18789/healthz > /dev/null 2>&1; do
  TRIES=$((TRIES + 1))
  if [ $TRIES -ge 30 ]; then
    echo "[entrypoint] ERROR: Gateway did not start after 60s"
    exit 1
  fi
  sleep 2
done
echo "[entrypoint] Gateway ready (PID $GATEWAY_PID)."

# ===========================================================
# 7. START MC SERVER
# ===========================================================
echo "[entrypoint] Starting Mission Control on :18790..."
node workspace-sancho/scripts/mc-server.js &
MC_PID=$!

echo "[entrypoint] All services running. Gateway=$GATEWAY_PID MC=$MC_PID"

# ===========================================================
# 8. WAIT — if either process dies, container stops
# ===========================================================
wait -n $GATEWAY_PID $MC_PID
EXIT_CODE=$?
echo "[entrypoint] A process exited with code $EXIT_CODE. Shutting down."
kill $GATEWAY_PID $MC_PID 2>/dev/null
exit $EXIT_CODE
