#!/bin/bash
set -e

cd /root/.openclaw

SETUP_DONE="/root/.openclaw/.setup-complete"

# ===========================================================
# 1-3. FIRST-RUN SETUP (skipped on restarts)
# ===========================================================
if [ ! -f "$SETUP_DONE" ]; then
  echo "[entrypoint] First run — configuring..."

  # 1. Generate openclaw.json from env vars + auto-detect Discord guilds
  echo "[entrypoint] Generating OpenClaw config..."
  node docker/generate-openclaw-config.js

  # 2. Register agents
  echo "[entrypoint] Registering agents..."
  bash docker/setup-agents.sh

  # 3. Inject env vars into .md files
  bash docker/inject-env-vars.sh

  # Mark setup as complete
  touch "$SETUP_DONE"
  echo "[entrypoint] Setup complete."
else
  echo "[entrypoint] Setup already done, skipping config generation."
fi

# ===========================================================
# 4. NODE DEPENDENCIES (ws for MC server)
# ===========================================================
if [ -f workspace-sancho/package.json ] && [ ! -d workspace-sancho/node_modules ]; then
  echo "[entrypoint] Installing Node dependencies..."
  (cd workspace-sancho && npm install --production --quiet)
fi

# ===========================================================
# 5. GENERATE MC DASHBOARD DATA (if missing)
# ===========================================================
if [ ! -f workspace-sancho/mission-control.html ] || [ ! -f workspace-sancho/agents-data.js ]; then
  echo "[entrypoint] Generating dashboard data..."
  (cd workspace-sancho && python3 scripts/regenerate.py 2>/dev/null) || \
    echo "[entrypoint] WARNING: regenerate.py failed (dashboard data will be generated by cron)"
fi

# ===========================================================
# 6. START GATEWAY (foreground, backgrounded for MC)
# ===========================================================
echo "[entrypoint] Starting OpenClaw gateway..."
openclaw gateway run &
GATEWAY_PID=$!

echo "[entrypoint] Waiting for gateway on :18789..."
TRIES=0
until curl -sf http://localhost:18789/healthz > /dev/null 2>&1; do
  TRIES=$((TRIES + 1))
  if [ $TRIES -ge 30 ]; then
    echo "[entrypoint] ERROR: Gateway did not start after 60s"
    exit 1
  fi
  sleep 2
done
echo "[entrypoint] Gateway ready (PID $GATEWAY_PID)."

# ===========================================================
# 7. START MC SERVER
# ===========================================================
echo "[entrypoint] Starting Mission Control on :18790..."
node workspace-sancho/scripts/mc-server.js &
MC_PID=$!

echo "[entrypoint] All services running. Gateway=$GATEWAY_PID MC=$MC_PID"

# ===========================================================
# 8. WAIT — if either process dies, container stops
# ===========================================================
wait -n $GATEWAY_PID $MC_PID
EXIT_CODE=$?
echo "[entrypoint] A process exited with code $EXIT_CODE. Shutting down."
kill $GATEWAY_PID $MC_PID 2>/dev/null
exit $EXIT_CODE
