// Auto-generated by scripts/regenerate-agents-data.py
// Last updated: 2026-04-04T18:02:03.107053+00:00

window.AGENTS_DATA = {
  "agents": [],
  "tasks": [],
  "lastUpdate": "2026-04-04T18:02:03.107278+00:00"
};
