// Auto-generated by regenerate script
// Last updated: 2026-04-03 16:01:30

const agentsData = [
  {
    "id": "hospital-capilar",
    "name": "Hospital Capilar",
    "positioning": "Sin posicionamiento definido",
    "status": "active",
    "lastActivity": "2026-04-03"
  },
  {
    "id": "growth4u",
    "name": "Growth4U",
    "positioning": "El sistema de growth para empresas tech en España que instala capacidad permanente, no dependencia.",
    "status": "inactive",
    "lastActivity": "2026-04-03"
  },
  {
    "id": "paymatico",
    "name": "Paymatico",
    "positioning": "Las ventajas de una fintech sin ser una — panel único de pagos, cuentas programables y marca blanca,",
    "status": "active",
    "lastActivity": "2026-04-03"
  },
  {
    "id": "sanchocmo",
    "name": "SanchoCMO - SelfMarketing",
    "positioning": "Do it yourself con un copiloto IA que aprende tu negocio — no es una agencia, no es un template",
    "status": "inactive",
    "lastActivity": "2026-04-03"
  },
  {
    "id": "kleva",
    "name": "KLEVA",
    "positioning": "Sin posicionamiento definido",
    "status": "active",
    "lastActivity": "2026-04-03"
  },
  {
    "id": "masabo",
    "name": "Masabo",
    "positioning": "Sin posicionamiento definido",
    "status": "active",
    "lastActivity": "2026-04-03"
  },
  {
    "id": "masavo",
    "name": "Masavo",
    "positioning": "Un lugar slow en una ciudad rápida",
    "status": "active",
    "lastActivity": "2026-04-03"
  },
  {
    "id": "dealcar",
    "name": "Dealcar",
    "positioning": "Sin posicionamiento definido",
    "status": "active",
    "lastActivity": "2026-04-03"
  },
  {
    "id": "criptan",
    "name": "Criptan",
    "positioning": "El complemento perfecto de tu banco — cripto seguro, regulado y rentable",
    "status": "active",
    "lastActivity": "2026-04-03"
  }
];
