#!/bin/bash
# memory-compact.sh — Archive daily notes >30d and generate monthly summaries
# Run: bash scripts/memory-compact.sh
# Cron: 1st of month

set -euo pipefail

WORKSPACE="${OPENCLAW_WORKSPACE:-$HOME/.openclaw/workspace-sancho}"
DAILY_DIR="$WORKSPACE/memory"
ARCHIVE_DIR="$WORKSPACE/memory/archive"
INDEX_FILE="$WORKSPACE/memory/INDEX.md"

mkdir -p "$ARCHIVE_DIR"

CUTOFF_DATE=$(date -v-30d +%Y-%m-%d 2>/dev/null || date -d "30 days ago" +%Y-%m-%d)
MOVED=0
ARCHIVED_FILES=""

echo "📦 Memory Compaction — $(date +%Y-%m-%d)"
echo "Cutoff: $CUTOFF_DATE (archiving notes older than this)"
echo ""

for f in "$DAILY_DIR"/20*.md; do
    [ -f "$f" ] || continue
    fname=$(basename "$f")
    # Extract date from filename (YYYY-MM-DD.md)
    fdate="${fname%.md}"
    
    if [[ "$fdate" < "$CUTOFF_DATE" ]]; then
        mv "$f" "$ARCHIVE_DIR/"
        MOVED=$((MOVED + 1))
        ARCHIVED_FILES="$ARCHIVED_FILES $fname"
        echo "  → archive/$fname"
    fi
done

echo ""
echo "✅ Archived $MOVED files."

# Generate monthly summary for archived months
for month_prefix in $(ls "$ARCHIVE_DIR"/20*.md 2>/dev/null | xargs -I{} basename {} | sed 's/-[0-9][0-9]\.md$//' | sort -u); do
    SUMMARY_FILE="$ARCHIVE_DIR/${month_prefix}-summary.md"
    
    # Skip if summary already exists and no new files
    if [ -f "$SUMMARY_FILE" ]; then
        continue
    fi
    
    echo "📝 Generating summary for $month_prefix..."
    
    {
        echo "# Monthly Summary — $month_prefix"
        echo ""
        echo "> Auto-generated by memory-compact.sh on $(date +%Y-%m-%d)"
        echo ""
        echo "## Files archived"
        for f in "$ARCHIVE_DIR"/${month_prefix}-*.md; do
            [ -f "$f" ] || continue
            fname=$(basename "$f")
            [[ "$fname" == *-summary.md ]] && continue
            echo "- $fname"
        done
        echo ""
        echo "## Key content"
        for f in "$ARCHIVE_DIR"/${month_prefix}-*.md; do
            [ -f "$f" ] || continue
            fname=$(basename "$f")
            [[ "$fname" == *-summary.md ]] && continue
            echo ""
            echo "### $fname"
            # Extract headers and first bullet under each
            grep -E "^##|^- " "$f" | head -10
        done
    } > "$SUMMARY_FILE"
    
    echo "  → archive/${month_prefix}-summary.md"
done

echo ""
echo "Done."
