#!/usr/bin/env python3
"""
Regenerate agents-data.js from sessions list and task tracker.
"""

import json
import subprocess
from pathlib import Path
from datetime import datetime, timezone

WORKSPACE = Path(__file__).parent.parent
AGENTS_DATA_FILE = WORKSPACE / "memory" / "mc" / "agents-data.js"

def run_command(cmd):
    """Run command and return JSON output."""
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if result.returncode != 0:
        return None
    try:
        return json.loads(result.stdout)
    except:
        return None

def main():
    # Get active sessions
    sessions_data = run_command("openclaw sessions list --json")
    sessions = sessions_data.get("sessions", []) if sessions_data else []
    
    # Get task tracker data
    task_tracker_path = WORKSPACE / "task-tracker.json"
    tasks = []
    if task_tracker_path.exists():
        with open(task_tracker_path) as f:
            tracker = json.load(f)
            tasks = tracker.get("tasks", [])
    
    # Build agent status data
    agents = []
    for session in sessions:
        agent_id = session.get("agentId", "unknown")
        session_key = session.get("sessionKey", "")
        label = session.get("label", "")
        
        # Match with tasks
        related_tasks = [
            task for task in tasks 
            if task.get("executor") == agent_id or task.get("sessionKey") == session_key
        ]
        
        agents.append({
            "agentId": agent_id,
            "sessionKey": session_key,
            "label": label,
            "status": "active",
            "tasks": len(related_tasks),
            "lastSeen": datetime.now(timezone.utc).isoformat()
        })
    
    # Generate JS file
    js_content = f"""// Auto-generated by scripts/regenerate-agents-data.py
// Last updated: {datetime.now(timezone.utc).isoformat()}

window.AGENTS_DATA = {json.dumps({
    "agents": agents,
    "tasks": tasks,
    "lastUpdate": datetime.now(timezone.utc).isoformat()
}, indent=2)};
"""
    
    AGENTS_DATA_FILE.write_text(js_content)
    print(f"✅ Written to {AGENTS_DATA_FILE}")
    print(f"   Agents: {len(agents)} active")
    print(f"   Tasks: {len(tasks)} total")

if __name__ == "__main__":
    main()
