#!/bin/bash
echo "🔄 Restarting gateway..."
openclaw gateway restart
sleep 5
echo "⏳ Waiting for Discord reconnect..."
sleep 10
openclaw status 2>&1 | grep "Discord"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ROUND 4 — messageId + thread:true"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  /new en cada canal antes de testear"
echo ""
echo "━━━ TEST A — Sancho responde (thread desde tu mensaje) ━━━"
echo "Canal: #brand"
echo "Escribe: Muéstrame el positioning"
echo ""
echo "  ✅ PASS: El hilo aparece DEBAJO de tu mensaje (vinculado)"
echo "           Respuesta dentro del hilo. Nada suelto en el canal."
echo "  ❌ FAIL: Hilo standalone (desconectado de tu mensaje)"
echo "           O texto de Sancho suelto en el canal"
echo ""
echo "━━━ TEST B — Gate check (thread desde tu mensaje) ━━━"
echo "Canal: #onboarding"
echo "Escribe: Ejecuta brand-voice"
echo ""
echo "  ✅ PASS: Hilo desde tu mensaje con ⛔ dentro. Nada en canal."
echo "  ❌ FAIL: Texto en canal o ejecuta sin verificar"
echo ""
echo "━━━ TEST C — Escudero (thread:true spawn) ━━━"
echo "Canal: #content"
echo "Escribe: Escribe un post de 500 palabras sobre PRP capilar"
echo ""
echo "  ✅ PASS: Escudero crea hilo y trabaja dentro. Canal limpio."
echo "  ❌ FAIL: Texto en canal o hilo vacío"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
