#!/bin/bash
echo "🔄 Restarting gateway..."
openclaw gateway restart
sleep 5
echo "⏳ Waiting for Discord reconnect..."
sleep 10
openclaw status 2>&1 | grep "Discord"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ROUND 3 — Foco en NO_REPLY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  /new en cada canal antes de testear"
echo ""
echo "━━━ TEST A — Respuesta simple ━━━"
echo "Canal: #content"
echo "Escribe: Genera un calendario editorial para marzo"
echo ""
echo "  ✅ PASS: Hilo creado, contenido SOLO dentro, NADA en canal"
echo "  ❌ FAIL: Cualquier texto visible en el canal"
echo ""
echo "━━━ TEST B — Gate check ━━━"
echo "Canal: #onboarding"
echo "Escribe: Ejecuta brand-voice"
echo ""
echo "  ✅ PASS: Hilo con ⛔ dentro, NADA en canal"
echo "  ❌ FAIL: Mensaje de bloqueo visible en canal"
echo ""
echo "━━━ TEST C — Subagente (el más difícil) ━━━"
echo "Canal: #content"
echo "Escribe: Escribe un post de blog de 800 palabras sobre mesoterapia capilar"
echo ""
echo "  ✅ PASS: Hilo → delega a Escudero → resultado dentro del hilo → NADA en canal"
echo "  ❌ FAIL: Resultado de Escudero aparece en el canal"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
