#!/bin/bash
# Round 2 verification — only the 3 failed tests
# Usage: bash ~/.openclaw/workspace-sancho/scripts/verify-round2.sh

echo "🔄 Restarting gateway..."
openclaw gateway restart
sleep 5
echo "⏳ Waiting for Discord reconnect..."
sleep 10

STATUS=$(openclaw status 2>&1 | grep "Discord")
echo "$STATUS"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ROUND 2 — Re-test de los 3 que fallaron"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  EN CADA CANAL, escribe /new PRIMERO"
echo ""
echo "━━━ TEST 1 — Threading + Links ━━━"
echo "Canal: #content"
echo "Escribe: Genera un calendario editorial para febrero"
echo ""
echo "  ✅ PASS si:"
echo "     - Crea hilo"
echo "     - NO escribe NADA en el canal (solo 'ha empezado un hilo')"
echo "     - Dentro del hilo: link como https://sancho-cmo.taild48df2.ts.net/mc/..."
echo "  ❌ FAIL si:"
echo "     - Escribe algo en el canal antes/después del hilo"
echo "     - Da ruta como brand/hospital-capilar/..."
echo ""
echo "━━━ TEST 3 — Gate Check ━━━"
echo "Canal: #onboarding"
echo "Escribe: Ejecuta visual-identity"
echo ""
echo "  ✅ PASS si:"
echo "     - Responde con ⛔ y dice que brand-voice no está aprobado"
echo "     - NO genera el documento"
echo "  ❌ FAIL si:"
echo "     - Empieza a ejecutar visual-identity"
echo "     - No menciona dependencias bloqueadas"
echo ""
echo "━━━ TEST 4 — Delegation a Escudero ━━━"
echo "Canal: #content"
echo "Escribe: Escribe un artículo SEO de 1500 palabras sobre trasplante capilar FUE"
echo ""
echo "  ✅ PASS si:"
echo "     - Menciona Escudero o sessions_spawn en su proceso"
echo "     - NO escribe el artículo completo él mismo"
echo "  ❌ FAIL si:"
echo "     - Escribe todo el artículo directamente (Opus desperdiciado)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Reporta resultados a Cervantes en webchat."
