/**
 * GET /api/share/:token/view — Serve a shared HTML deliverable with the
 * comments layer injected (SAN-148).
 *
 * Token-authenticated like the sibling endpoints. Returns the ORIGINAL
 * HTML (never the `.commented` transcript sibling — comments overlay from
 * the DB via comments-embed.js) with
 *   <script src="/comments-embed.js" data-api="/api/share/<token>/comments" defer></script>
 * injected before </body>. The share page renders this URL in an iframe
 * with allow-scripts so selection → comment works inside the deliverable.
 *
 * Security note: the iframe uses allow-scripts + allow-same-origin, which
 * with same-origin content disables sandbox isolation. Accepted: shared
 * HTML deliverables are first-party output generated by our own agents
 * under brand/{slug}/ — not arbitrary user uploads. Revisit (serve from a
 * separate origin) if that ever changes.
 */

import type { NextApiRequest, NextApiResponse } from "next";
import fs from "fs";
import path from "path";
import { withErrorHandler } from "@/lib/api-middleware";
import { getOriginalDocPath } from "@/lib/comments-file";
import { BASE } from "@/lib/data/paths";
import { verifyShareToken } from "@/lib/share-tokens";
import { resolveWorkspaceDocPath } from "@/lib/server/doc-paths";

async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "GET") {
    res.setHeader("Allow", "GET");
    return res.status(405).json({ error: `Method ${req.method} not allowed` });
  }

  const { token } = req.query;
  const tokenStr = Array.isArray(token) ? token[0] : token;
  if (!tokenStr) return res.status(400).json({ error: "Missing token" });

  const payload = verifyShareToken(tokenStr);
  if (!payload) {
    return res.status(403).json({ error: "Invalid or expired share token" });
  }
  if (!payload.docPath.startsWith(`brand/${payload.slug}/`)) {
    return res.status(403).json({ error: "Token payload mismatch" });
  }

  // Always the clean original — the `.commented` sibling is a feedback
  // transcript, not a renderable deliverable.
  const originalDocPath = getOriginalDocPath(payload.docPath);

  let resolved;
  try {
    resolved = resolveWorkspaceDocPath(BASE, originalDocPath, {
      slug: payload.slug,
      requireBrand: true,
    });
  } catch {
    return res.status(403).json({ error: "Forbidden" });
  }
  if (!resolved.exists || !fs.existsSync(resolved.absPath)) {
    return res.status(404).json({ error: "Not found" });
  }
  if (path.extname(resolved.absPath).toLowerCase() !== ".html") {
    return res.status(400).json({ error: "Not an HTML document" });
  }

  let html = fs.readFileSync(resolved.absPath, "utf-8");
  const snippet = `<script src="/comments-embed.js" data-api="/api/share/${encodeURIComponent(
    tokenStr,
  )}/comments" defer></script>`;
  if (/<\/body>/i.test(html)) {
    html = html.replace(/<\/body>/i, `${snippet}\n</body>`);
  } else {
    html += `\n${snippet}\n`;
  }

  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.setHeader("X-Robots-Tag", "noindex");
  res.setHeader("Cache-Control", "no-store");
  return res.status(200).send(html);
}

export default withErrorHandler(handler);
