import type {
  DashboardArea,
  MetricDefinition,
  MetricDefinitionGroup,
  MetricFamily,
  MetricSourceRef,
} from "@/lib/metrics/semantic-types";

type MetricSeed = {
  id: string;
  label: string;
  family: MetricFamily;
  area: DashboardArea;
  description: string;
} & Partial<Omit<MetricDefinition, "id" | "label" | "family" | "area" | "description">>;

function src(source: string, metric?: string, role: MetricSourceRef["role"] = "primary", dimensions?: Record<string, string>): MetricSourceRef {
  return { source, metric, role, dimensions };
}

function metric(seed: MetricSeed): MetricDefinition {
  return {
    format: "number",
    aggregation: "sum",
    calculationKind: "direct",
    status: "partial",
    sources: [],
    ...seed,
  };
}

function group(id: string, title: string, area: DashboardArea, definitions: MetricDefinition[]): MetricDefinitionGroup {
  return { id, title, area, definitions };
}

export const REQUIRED_DASHBOARD_METRIC_IDS = [
  "overview.north_star",
  "overview.north_star_inputs",
  "overview.investment",
  "overview.cac",
  "overview.generated_revenue",
  "overview.roas",
  "overview.unified_funnel",
  "overview.surface_health",
  "overview.alerts_bridge",
  "web.gsc_clicks",
  "web.gsc_impressions",
  "web.gsc_ctr",
  "web.gsc_position",
  "web.ga4_sessions",
  "web.ga4_engagement",
  "web.ga4_conversions",
  "web.pagespeed_cwv",
  "web.query_breakdown",
  "web.page_breakdown",
  "web.channel_breakdown",
  "web.device_breakdown",
  "web.country_breakdown",
  "web.seo_movers",
  "web.aeo_geo_visibility",
  "paid.spend",
  "paid.pacing",
  "paid.cpa_platform",
  "paid.revenue_platform",
  "paid.roas_platform",
  "paid.conversions",
  "paid.ctr",
  "paid.cpc",
  "paid.impression_share",
  "paid.lost_impression_share",
  "paid.platform_breakdown",
  "paid.campaign_breakdown",
  "paid.placement_breakdown",
  "paid.audience_breakdown",
  "paid.keyword_breakdown",
  "paid.creative_metrics",
  "paid.fatigue",
  "paid.learning_state",
  "reputation.trust_score",
  "reputation.gap_vs_leader",
  "reputation.ai_presence",
  "reputation.reviews",
  "reputation.competitors",
  "reputation.pillar_scores",
  "reputation.benchmark",
  "reputation.competitor_detail",
  "reputation.diagnosis",
  "reputation.listening_sov",
  "reputation.sentiment",
  "pipeline.open_pipeline",
  "pipeline.weighted_forecast",
  "pipeline.closed_won",
  "pipeline.win_rate",
  "pipeline.average_deal_size",
  "pipeline.sales_cycle",
  "pipeline.velocity",
  "pipeline.coverage",
  "pipeline.waterfall",
  "pipeline.stage_funnel",
  "pipeline.forecast_vs_quota",
  "pipeline.open_deals_aging",
  "pipeline.risk_health",
  "product.activation_rate",
  "product.north_star_event",
  "product.dau",
  "product.wau",
  "product.mau",
  "product.stickiness",
  "product.d30_retention",
  "product.time_to_value",
  "product.feature_adoption",
  "product.returning_vs_new",
  "product.activation_funnel",
  "product.cohort_heatmap",
  "product.friction_queue",
  "social.impressions",
  "social.reach",
  "social.engagement_rate",
  "social.followers_net_growth",
  "social.posts",
  "social.clicks_visits",
  "social.video_views",
  "social.shares_saves",
  "social.network_scorecard",
  "social.top_posts",
  "social.best_time",
  "social.format_bars",
  "outbound.icp.sent",
  "outbound.icp.reply_rate",
  "outbound.icp.positive_reply",
  "outbound.icp.meetings_booked",
  "outbound.icp.bounce_rate",
  "outbound.icp.open_rate_mpp",
  "outbound.icp.opt_out",
  "outbound.icp.spam_complaint",
  "outbound.icp.sequence_funnel",
  "outbound.icp.reply_by_step",
  "outbound.icp.ab_compare",
  "outbound.icp.deliverability_health",
  "outbound.partnerships.invested",
  "outbound.partnerships.cpa_real",
  "outbound.partnerships.generated_value",
  "outbound.partnerships.roi",
  "outbound.partnerships.clicks",
  "outbound.partnerships.signups",
  "outbound.partnerships.kyc_approved",
  "outbound.partnerships.first_transaction",
  "outbound.partnerships.creator_leaderboard",
  "outbound.partnerships.cpa_vs_break_even",
  "outbound.partnerships.renew_watch_cut",
  "channels.attribution_model",
  "channels.mini_funnel",
  "channels.stage_matrix",
  "channels.contribution_table",
  "channels.model_comparison",
  "channels.journeys",
  "channels.signals_bridge",
  "conversion.end_to_end_funnel",
  "conversion.stage_rates",
  "conversion.by_channel_matrix",
  "conversion.velocity",
  "conversion.leak_panel",
  "conversion.signals_bridge",
  "trends.north_star_hero",
  "trends.kpi_small_multiples",
  "trends.granularity",
  "trends.compare_previous",
  "trends.compare_year",
  "trends.compare_target",
  "trends.annotations",
  "trends.signals_bridge",
] as const;

export const DASHBOARD_METRIC_GROUPS: MetricDefinitionGroup[] = [
  group("overview", "Overview", "overview", [
    metric({
      id: "overview.north_star",
      label: "North Star",
      family: "overview",
      area: "overview",
      description: "Client-selected primary business outcome for the dashboard range.",
      format: "number",
      aggregation: "latest",
      calculationKind: "derived",
      status: "requires_mapping",
      sources: [src("metric_kpi_values", "north_star"), src("metric_funnel_stage_map", "north_star_stage", "input")],
    }),
    metric({
      id: "overview.north_star_inputs",
      label: "North Star inputs",
      family: "overview",
      area: "overview",
      description: "Drivers that explain the North Star movement.",
      calculationKind: "rollup",
      status: "requires_mapping",
      sources: [src("metric_kpi_values", undefined, "input"), src("metric_stage_rollups", undefined, "stage")],
    }),
    metric({
      id: "overview.investment",
      label: "Investment",
      family: "overview",
      area: "overview",
      description: "Paid spend plus partnerships investment when available.",
      format: "currency",
      calculationKind: "rollup",
      sources: [src("meta-ads", "spend", "cost"), src("google_ads", "cost_micros", "cost"), src("yalc", "invested", "cost")],
    }),
    metric({
      id: "overview.cac",
      label: "CAC",
      family: "overview",
      area: "overview",
      description: "Acquisition cost divided by new customers from reliable downstream sources.",
      format: "currency",
      aggregation: "computed",
      calculationKind: "ratio",
      status: "requires_mapping",
      sources: [src("metric_kpi_values", "investment", "cost"), src("metric_stage_rollups", "customer", "stage")],
      dependsOn: ["overview.investment", "conversion.end_to_end_funnel"],
    }),
    metric({
      id: "overview.generated_revenue",
      label: "Generated revenue",
      family: "overview",
      area: "overview",
      description: "Real closed-won or payment revenue, not platform pixel revenue.",
      format: "currency",
      calculationKind: "rollup",
      status: "requires_mapping",
      sources: [src("ghl", "closedWonValue", "revenue"), src("stripe", "net_revenue", "revenue"), src("koibox", "paid_revenue", "revenue")],
    }),
    metric({
      id: "overview.roas",
      label: "ROAS",
      family: "overview",
      area: "overview",
      description: "Real revenue divided by investment.",
      format: "ratio",
      aggregation: "computed",
      calculationKind: "ratio",
      status: "requires_mapping",
      sources: [src("metric_kpi_values", "generated_revenue", "revenue"), src("metric_kpi_values", "investment", "cost")],
      dependsOn: ["overview.generated_revenue", "overview.investment"],
    }),
    metric({
      id: "overview.unified_funnel",
      label: "Unified funnel",
      family: "overview",
      area: "overview",
      description: "Business-stage rollup across all surfaces.",
      calculationKind: "stage_rollup",
      status: "requires_mapping",
      sources: [src("metric_stage_rollups", undefined, "stage"), src("metric_funnel_stage_map", undefined, "input")],
    }),
    metric({
      id: "overview.surface_health",
      label: "Surface health",
      family: "overview",
      area: "overview",
      description: "Status and headline KPI for each active surface.",
      aggregation: "latest",
      calculationKind: "rollup",
      sources: [src("metric_kpi_values", undefined, "quality"), src("metric_source_runs", undefined, "quality")],
    }),
    metric({
      id: "overview.alerts_bridge",
      label: "Movements and alerts bridge",
      family: "overview",
      area: "overview",
      description: "Entry point for metric movements and future Intelligence alerts.",
      aggregation: "latest",
      calculationKind: "derived",
      status: "planned",
      sources: [src("metric_signals", undefined, "quality")],
    }),
  ]),
  group("web", "Discoverability / Web & SEO", "surfaces", [
    metric({ id: "web.gsc_clicks", label: "GSC clicks", family: "web", area: "surfaces", surface: "web", description: "Organic search clicks from Search Console.", sources: [src("gsc", "clicks")] }),
    metric({ id: "web.gsc_impressions", label: "GSC impressions", family: "web", area: "surfaces", surface: "web", description: "Organic search impressions from Search Console.", sources: [src("gsc", "impressions")] }),
    metric({ id: "web.gsc_ctr", label: "GSC CTR", family: "web", area: "surfaces", surface: "web", description: "Organic search click-through rate.", format: "percent", aggregation: "avg", calculationKind: "ratio", sources: [src("gsc", "ctr")] }),
    metric({ id: "web.gsc_position", label: "GSC position", family: "web", area: "surfaces", surface: "web", description: "Average search ranking position.", format: "number", aggregation: "avg", sources: [src("gsc", "position")] }),
    metric({ id: "web.ga4_sessions", label: "GA4 sessions", family: "web", area: "surfaces", surface: "web", description: "Website sessions from GA4.", sources: [src("ga4", "sessions")] }),
    metric({ id: "web.ga4_engagement", label: "GA4 engagement", family: "web", area: "surfaces", surface: "web", description: "Engagement rate or engaged sessions from GA4.", format: "percent", aggregation: "avg", sources: [src("ga4", "engagementRate"), src("ga4", "engagedSessions", "input")] }),
    metric({ id: "web.ga4_conversions", label: "GA4 conversions", family: "web", area: "surfaces", surface: "web", description: "Configured GA4 conversion events.", sources: [src("ga4", "conversions")] }),
    metric({ id: "web.pagespeed_cwv", label: "Core Web Vitals", family: "web", area: "surfaces", surface: "web", description: "PageSpeed performance and Core Web Vitals latest run.", format: "score", aggregation: "latest", sources: [src("pagespeed", "performance_mobile"), src("pagespeed", "lcp_mobile", "input"), src("pagespeed", "cls_mobile", "input"), src("pagespeed", "inp_mobile", "input")] }),
    metric({ id: "web.query_breakdown", label: "Query breakdown", family: "web", area: "surfaces", surface: "web", description: "Search metrics by query.", requiredDimensions: ["query"], sources: [src("gsc", "clicks", "primary", { dimension: "query" })] }),
    metric({ id: "web.page_breakdown", label: "Page breakdown", family: "web", area: "surfaces", surface: "web", description: "Search and traffic metrics by landing page.", requiredDimensions: ["page"], sources: [src("gsc", "clicks", "primary", { dimension: "page" }), src("ga4", "sessions", "input", { dimension: "page" })] }),
    metric({ id: "web.channel_breakdown", label: "Channel breakdown", family: "web", area: "surfaces", surface: "web", description: "Traffic and conversion split by channel.", requiredDimensions: ["channel"], sources: [src("ga4", "sessions", "primary", { dimension: "channel" })] }),
    metric({ id: "web.device_breakdown", label: "Device breakdown", family: "web", area: "surfaces", surface: "web", description: "Traffic and conversion split by device.", requiredDimensions: ["device"], sources: [src("ga4", "sessions", "primary", { dimension: "device" }), src("gsc", "clicks", "input", { dimension: "device" })] }),
    metric({ id: "web.country_breakdown", label: "Country breakdown", family: "web", area: "surfaces", surface: "web", description: "Traffic and search split by country.", requiredDimensions: ["country"], sources: [src("ga4", "sessions", "primary", { dimension: "country" }), src("gsc", "clicks", "input", { dimension: "country" })] }),
    metric({ id: "web.seo_movers", label: "SEO movers", family: "web", area: "surfaces", surface: "web", description: "Largest query or page gains and losses versus previous period.", aggregation: "computed", calculationKind: "derived", sources: [src("gsc", "clicks"), src("gsc", "position", "input")] }),
    metric({ id: "web.aeo_geo_visibility", label: "AEO/GEO visibility", family: "web", area: "surfaces", surface: "web", description: "Future AI search presence and answer visibility metrics.", aggregation: "latest", calculationKind: "manual", status: "planned", sources: [src("ai_search", "presence")] }),
  ]),
  group("paid", "Paid", "surfaces", [
    metric({ id: "paid.spend", label: "Spend", family: "paid", area: "surfaces", surface: "paid", description: "Media spend by paid platform.", format: "currency", sources: [src("meta-ads", "spend", "cost"), src("google_ads", "cost_micros", "cost"), src("linkedin_ads", "spend", "cost")] }),
    metric({ id: "paid.pacing", label: "Pacing", family: "paid", area: "surfaces", surface: "paid", description: "Spend pace against configured budget.", format: "percent", aggregation: "computed", calculationKind: "ratio", status: "requires_mapping", sources: [src("metric_kpi_values", "paid.spend"), src("metric_definitions", "budget", "input")] }),
    metric({ id: "paid.cpa_platform", label: "CPA platform", family: "paid", area: "surfaces", surface: "paid", description: "Platform-reported cost per conversion.", format: "currency", aggregation: "avg", calculationKind: "ratio", sources: [src("meta-ads", "cpa"), src("google_ads", "cost_per_conversion")] }),
    metric({ id: "paid.revenue_platform", label: "Revenue platform", family: "paid", area: "surfaces", surface: "paid", description: "Platform-attributed revenue, explicitly separate from real revenue.", format: "currency", sources: [src("meta-ads", "purchase_value"), src("google_ads", "conversion_value")] }),
    metric({ id: "paid.roas_platform", label: "ROAS platform", family: "paid", area: "surfaces", surface: "paid", description: "Platform-attributed revenue divided by platform spend.", format: "ratio", aggregation: "avg", calculationKind: "ratio", sources: [src("meta-ads", "roas"), src("google_ads", "roas")] }),
    metric({ id: "paid.conversions", label: "Conversions", family: "paid", area: "surfaces", surface: "paid", description: "Platform-reported conversions.", sources: [src("meta-ads", "conversions"), src("google_ads", "conversions"), src("linkedin_ads", "conversions")] }),
    metric({ id: "paid.ctr", label: "CTR", family: "paid", area: "surfaces", surface: "paid", description: "Paid click-through rate.", format: "percent", aggregation: "avg", calculationKind: "ratio", sources: [src("meta-ads", "ctr"), src("google_ads", "ctr"), src("linkedin_ads", "ctr")] }),
    metric({ id: "paid.cpc", label: "CPC", family: "paid", area: "surfaces", surface: "paid", description: "Paid cost per click.", format: "currency", aggregation: "avg", calculationKind: "ratio", sources: [src("meta-ads", "cpc"), src("google_ads", "average_cpc"), src("linkedin_ads", "cpc")] }),
    metric({ id: "paid.impression_share", label: "Impression share", family: "paid", area: "surfaces", surface: "paid", description: "Eligible impression share where platforms expose it.", format: "percent", aggregation: "avg", status: "planned", sources: [src("google_ads", "search_impression_share"), src("linkedin_ads", "impression_share")] }),
    metric({ id: "paid.lost_impression_share", label: "Lost impression share", family: "paid", area: "surfaces", surface: "paid", description: "Lost impression share due to budget or rank.", format: "percent", aggregation: "avg", status: "planned", sources: [src("google_ads", "search_budget_lost_impression_share"), src("google_ads", "search_rank_lost_impression_share")] }),
    metric({ id: "paid.platform_breakdown", label: "Platform breakdown", family: "paid", area: "surfaces", surface: "paid", description: "Paid performance grouped by platform.", requiredDimensions: ["platform"], sources: [src("metric_snapshots", "spend", "primary", { dimension: "platform" })] }),
    metric({ id: "paid.campaign_breakdown", label: "Campaign breakdown", family: "paid", area: "surfaces", surface: "paid", description: "Paid performance grouped by campaign.", requiredDimensions: ["campaign"], sources: [src("meta-ads", "spend", "primary", { dimension: "campaign" }), src("google_ads", "cost_micros", "input", { dimension: "campaign" })] }),
    metric({ id: "paid.placement_breakdown", label: "Placement breakdown", family: "paid", area: "surfaces", surface: "paid", description: "Paid performance grouped by placement/network.", requiredDimensions: ["placement"], sources: [src("meta-ads", "spend", "primary", { dimension: "placement" })] }),
    metric({ id: "paid.audience_breakdown", label: "Audience breakdown", family: "paid", area: "surfaces", surface: "paid", description: "Paid performance grouped by audience/ad set.", requiredDimensions: ["audience"], sources: [src("meta-ads", "spend", "primary", { dimension: "audience" }), src("meta-ads", "spend", "input", { dimension: "adset" })] }),
    metric({ id: "paid.keyword_breakdown", label: "Keyword breakdown", family: "paid", area: "surfaces", surface: "paid", description: "Paid search performance grouped by keyword.", requiredDimensions: ["keyword"], status: "planned", sources: [src("google_ads", "cost_micros", "primary", { dimension: "keyword" })] }),
    metric({ id: "paid.creative_metrics", label: "Creative metrics", family: "paid", area: "surfaces", surface: "paid", description: "Creative-level spend, engagement and conversion metrics.", requiredDimensions: ["creative"], sources: [src("meta-ads", "spend", "primary", { dimension: "ad" })] }),
    metric({ id: "paid.fatigue", label: "Fatigue", family: "paid", area: "surfaces", surface: "paid", description: "Creative or audience fatigue inferred from frequency and performance decay.", format: "score", aggregation: "computed", calculationKind: "derived", sources: [src("meta-ads", "frequency"), src("meta-ads", "ctr", "input")] }),
    metric({ id: "paid.learning_state", label: "Learning state", family: "paid", area: "surfaces", surface: "paid", description: "Platform learning or delivery state when available.", format: "text", aggregation: "latest", status: "planned", sources: [src("meta-ads", "learning_phase"), src("google_ads", "serving_status")] }),
  ]),
  group("reputation", "Reputation", "surfaces", [
    metric({ id: "reputation.trust_score", label: "Trust Score", family: "reputation", area: "surfaces", surface: "reputation", description: "Sancho internal trust score.", format: "score", aggregation: "latest", sources: [src("trust_score", "trust_score")] }),
    metric({ id: "reputation.gap_vs_leader", label: "Gap vs leader", family: "reputation", area: "surfaces", surface: "reputation", description: "Trust Score or pillar gap against leading competitor.", format: "score", aggregation: "latest", calculationKind: "derived", sources: [src("trust_score", "competitor_gap")] }),
    metric({ id: "reputation.ai_presence", label: "AI presence", family: "reputation", area: "surfaces", surface: "reputation", description: "Brand presence in AI answer checks.", format: "score", aggregation: "latest", status: "partial", sources: [src("trust_score", "ai_presence")] }),
    metric({ id: "reputation.reviews", label: "Reviews", family: "reputation", area: "surfaces", surface: "reputation", description: "Review volume and rating metrics.", format: "score", aggregation: "latest", status: "planned", sources: [src("reviews", "rating"), src("reviews", "count", "input")] }),
    metric({ id: "reputation.competitors", label: "Competitors", family: "reputation", area: "surfaces", surface: "reputation", description: "Configured competitor set for benchmarks.", format: "text", aggregation: "latest", sources: [src("trust_score", "competitors")] }),
    metric({ id: "reputation.pillar_scores", label: "6 pillars", family: "reputation", area: "surfaces", surface: "reputation", description: "Six-pillar reputation scorecard.", format: "score", aggregation: "latest", requiredDimensions: ["pillar"], sources: [src("trust_score", "pillar_score", "primary", { dimension: "pillar" })] }),
    metric({ id: "reputation.benchmark", label: "Benchmark", family: "reputation", area: "surfaces", surface: "reputation", description: "Competitor benchmark across Trust Score and pillars.", format: "score", aggregation: "latest", requiredDimensions: ["competitor"], sources: [src("trust_score", "benchmark", "primary", { dimension: "competitor" })] }),
    metric({ id: "reputation.competitor_detail", label: "Competitor detail", family: "reputation", area: "surfaces", surface: "reputation", description: "Per-competitor diagnostic details.", format: "text", aggregation: "latest", requiredDimensions: ["competitor"], sources: [src("trust_score", "competitor_detail", "primary", { dimension: "competitor" })] }),
    metric({ id: "reputation.diagnosis", label: "Diagnosis", family: "reputation", area: "surfaces", surface: "reputation", description: "Trust Engine diagnosis and actions.", format: "text", aggregation: "latest", sources: [src("trust_score", "diagnosis")] }),
    metric({ id: "reputation.listening_sov", label: "Listening / SoV", family: "reputation", area: "surfaces", surface: "reputation", description: "Future share-of-voice and listening metrics.", format: "percent", aggregation: "avg", status: "planned", sources: [src("listening", "share_of_voice")] }),
    metric({ id: "reputation.sentiment", label: "Sentiment", family: "reputation", area: "surfaces", surface: "reputation", description: "Future review/social sentiment metrics.", format: "score", aggregation: "avg", status: "planned", sources: [src("listening", "sentiment")] }),
  ]),
  group("pipeline", "Pipeline / CRM", "surfaces", [
    metric({ id: "pipeline.open_pipeline", label: "Open pipeline", family: "pipeline", area: "surfaces", surface: "pipeline", description: "Current open pipeline value.", format: "currency", aggregation: "latest", sources: [src("ghl", "pipelineValue"), src("hubspot", "open_pipeline")] }),
    metric({ id: "pipeline.weighted_forecast", label: "Weighted forecast", family: "pipeline", area: "surfaces", surface: "pipeline", description: "Probability-weighted pipeline forecast.", format: "currency", aggregation: "latest", calculationKind: "forecast", status: "requires_mapping", sources: [src("crm", "weighted_forecast")] }),
    metric({ id: "pipeline.closed_won", label: "Closed-won", family: "pipeline", area: "surfaces", surface: "pipeline", description: "Closed-won revenue in the range.", format: "currency", sources: [src("ghl", "closedWonValue"), src("hubspot", "closed_won_amount")] }),
    metric({ id: "pipeline.win_rate", label: "Win rate", family: "pipeline", area: "surfaces", surface: "pipeline", description: "Closed-won deals divided by closed opportunities.", format: "percent", aggregation: "avg", calculationKind: "ratio", status: "requires_mapping", sources: [src("crm", "closed_won_count"), src("crm", "closed_lost_count", "input")] }),
    metric({ id: "pipeline.average_deal_size", label: "Average deal size", family: "pipeline", area: "surfaces", surface: "pipeline", description: "Average closed-won deal value.", format: "currency", aggregation: "avg", calculationKind: "ratio", sources: [src("ghl", "closedWonValue"), src("ghl", "closedWonCount", "input")] }),
    metric({ id: "pipeline.sales_cycle", label: "Sales cycle", family: "pipeline", area: "surfaces", surface: "pipeline", description: "Average days from lead to closed-won.", format: "duration", aggregation: "avg", calculationKind: "event", status: "requires_mapping", sources: [src("metric_stage_events", "days_to_close")] }),
    metric({ id: "pipeline.velocity", label: "Velocity", family: "pipeline", area: "surfaces", surface: "pipeline", description: "Pipeline velocity from deal count, value, win rate and cycle length.", format: "currency", aggregation: "computed", calculationKind: "derived", status: "requires_mapping", sources: [src("metric_kpi_values", "pipeline.win_rate"), src("metric_kpi_values", "pipeline.average_deal_size", "input"), src("metric_kpi_values", "pipeline.sales_cycle", "input")] }),
    metric({ id: "pipeline.coverage", label: "Coverage", family: "pipeline", area: "surfaces", surface: "pipeline", description: "Pipeline coverage against quota or target.", format: "ratio", aggregation: "computed", calculationKind: "ratio", status: "requires_mapping", sources: [src("crm", "pipelineValue"), src("metric_definitions", "quota", "input")] }),
    metric({ id: "pipeline.waterfall", label: "Pipeline waterfall", family: "pipeline", area: "surfaces", surface: "pipeline", description: "Pipeline movement by created, progressed, won and lost.", format: "currency", calculationKind: "event", status: "requires_mapping", sources: [src("metric_stage_events", "pipeline_change")] }),
    metric({ id: "pipeline.stage_funnel", label: "Stage funnel", family: "pipeline", area: "surfaces", surface: "pipeline", description: "CRM stage counts and conversion rates.", calculationKind: "stage_rollup", status: "requires_mapping", requiredDimensions: ["stage"], sources: [src("metric_stage_rollups", undefined, "stage", { dimension: "stage" })] }),
    metric({ id: "pipeline.forecast_vs_quota", label: "Forecast vs quota", family: "pipeline", area: "surfaces", surface: "pipeline", description: "Forecast progress against configured quota.", format: "percent", aggregation: "computed", calculationKind: "ratio", status: "requires_mapping", sources: [src("crm", "weighted_forecast"), src("metric_definitions", "quota", "input")] }),
    metric({ id: "pipeline.open_deals_aging", label: "Open deals + aging", family: "pipeline", area: "surfaces", surface: "pipeline", description: "Open deals table with days in stage.", format: "duration", aggregation: "avg", calculationKind: "event", status: "requires_mapping", requiredDimensions: ["deal"], sources: [src("metric_stage_events", "days_in_stage", "primary", { dimension: "deal" })] }),
    metric({ id: "pipeline.risk_health", label: "Risk health", family: "pipeline", area: "surfaces", surface: "pipeline", description: "Deal and forecast risks based on age, stage and quality flags.", format: "score", aggregation: "latest", calculationKind: "derived", status: "requires_mapping", sources: [src("metric_signals", "pipeline_risk")] }),
  ]),
  group("product", "Product", "surfaces", [
    metric({ id: "product.activation_rate", label: "Activation rate", family: "product", area: "surfaces", surface: "product", description: "Activated users divided by eligible signups.", format: "percent", aggregation: "avg", calculationKind: "ratio", sources: [src("posthog", "activation_rate"), src("ga4", "activation_rate")] }),
    metric({ id: "product.north_star_event", label: "North Star event", family: "product", area: "surfaces", surface: "product", description: "Configured product activation or value event.", sources: [src("posthog", "north_star_event")] }),
    metric({ id: "product.dau", label: "DAU", family: "product", area: "surfaces", surface: "product", description: "Daily active users.", aggregation: "latest", sources: [src("posthog", "dau")] }),
    metric({ id: "product.wau", label: "WAU", family: "product", area: "surfaces", surface: "product", description: "Weekly active users.", aggregation: "latest", sources: [src("posthog", "wau")] }),
    metric({ id: "product.mau", label: "MAU", family: "product", area: "surfaces", surface: "product", description: "Monthly active users.", aggregation: "latest", sources: [src("posthog", "mau")] }),
    metric({ id: "product.stickiness", label: "Stickiness", family: "product", area: "surfaces", surface: "product", description: "DAU divided by MAU.", format: "percent", aggregation: "avg", calculationKind: "ratio", status: "requires_mapping", sources: [src("posthog", "dau"), src("posthog", "mau", "input")] }),
    metric({ id: "product.d30_retention", label: "D30 retention", family: "product", area: "surfaces", surface: "product", description: "Day-30 retention cohort metric.", format: "percent", aggregation: "avg", status: "planned", sources: [src("posthog", "d30_retention")] }),
    metric({ id: "product.time_to_value", label: "Time to value", family: "product", area: "surfaces", surface: "product", description: "Time from signup to activation event.", format: "duration", aggregation: "avg", calculationKind: "event", status: "requires_mapping", sources: [src("metric_stage_events", "time_to_value")] }),
    metric({ id: "product.feature_adoption", label: "Feature adoption", family: "product", area: "surfaces", surface: "product", description: "Adoption by feature or event.", format: "percent", aggregation: "avg", requiredDimensions: ["feature"], sources: [src("posthog", "feature_adoption", "primary", { dimension: "feature" })] }),
    metric({ id: "product.returning_vs_new", label: "Returning vs new", family: "product", area: "surfaces", surface: "product", description: "Returning and new user split.", requiredDimensions: ["user_type"], sources: [src("posthog", "active_users", "primary", { dimension: "user_type" })] }),
    metric({ id: "product.activation_funnel", label: "Activation funnel", family: "product", area: "surfaces", surface: "product", description: "Product activation funnel steps.", calculationKind: "stage_rollup", requiredDimensions: ["stage"], sources: [src("posthog", "funnel_step_reached", "stage", { dimension: "stage" })] }),
    metric({ id: "product.cohort_heatmap", label: "Cohort heatmap", family: "product", area: "surfaces", surface: "product", description: "Retention cohort matrix.", format: "percent", aggregation: "avg", status: "planned", requiredDimensions: ["cohort", "period"], sources: [src("posthog", "retention", "primary", { dimension: "cohort" })] }),
    metric({ id: "product.friction_queue", label: "Friction queue", family: "product", area: "surfaces", surface: "product", description: "Product friction signals from recordings and events.", format: "text", aggregation: "latest", status: "planned", sources: [src("posthog", "friction"), src("metric_signals", "product_friction", "quality")] }),
  ]),
  group("social", "Social", "surfaces", [
    metric({ id: "social.impressions", label: "Impressions", family: "social", area: "surfaces", surface: "social", description: "Social impressions.", sources: [src("metricool", "impressions")] }),
    metric({ id: "social.reach", label: "Reach", family: "social", area: "surfaces", surface: "social", description: "Social reach.", status: "planned", sources: [src("metricool", "reach")] }),
    metric({ id: "social.engagement_rate", label: "Engagement rate", family: "social", area: "surfaces", surface: "social", description: "Engagement rate with explicit denominator.", format: "percent", aggregation: "avg", calculationKind: "ratio", sources: [src("metricool", "avgEngagement")] }),
    metric({ id: "social.followers_net_growth", label: "Followers / net growth", family: "social", area: "surfaces", surface: "social", description: "Follower count and net growth.", aggregation: "latest", status: "planned", sources: [src("metricool", "followers"), src("metricool", "followers_net_growth", "input")] }),
    metric({ id: "social.posts", label: "Posts", family: "social", area: "surfaces", surface: "social", description: "Published posts count.", sources: [src("metricool", "posts")] }),
    metric({ id: "social.clicks_visits", label: "Clicks / visits", family: "social", area: "surfaces", surface: "social", description: "Social outbound clicks or visits.", sources: [src("metricool", "clicks"), src("ga4", "sessions", "input", { channel: "social" })] }),
    metric({ id: "social.video_views", label: "Video views", family: "social", area: "surfaces", surface: "social", description: "Video views across social posts.", status: "planned", sources: [src("metricool", "video_views")] }),
    metric({ id: "social.shares_saves", label: "Shares / saves", family: "social", area: "surfaces", surface: "social", description: "Shares and saves across social posts.", status: "planned", sources: [src("metricool", "shares"), src("metricool", "saves", "input")] }),
    metric({ id: "social.network_scorecard", label: "Network scorecard", family: "social", area: "surfaces", surface: "social", description: "Metrics grouped by social network.", requiredDimensions: ["network"], sources: [src("metricool", "impressions", "primary", { dimension: "network" })] }),
    metric({ id: "social.top_posts", label: "Top posts", family: "social", area: "surfaces", surface: "social", description: "Top social posts by configured metric.", requiredDimensions: ["post"], sources: [src("metricool", "postDetail", "primary", { dimension: "post" })] }),
    metric({ id: "social.best_time", label: "Best time", family: "social", area: "surfaces", surface: "social", description: "Best posting time heatmap.", status: "planned", requiredDimensions: ["hour", "day_of_week"], sources: [src("metricool", "impressions", "primary", { dimension: "hour" })] }),
    metric({ id: "social.format_bars", label: "Format bars", family: "social", area: "surfaces", surface: "social", description: "Performance grouped by content format.", status: "planned", requiredDimensions: ["format"], sources: [src("metricool", "impressions", "primary", { dimension: "format" })] }),
  ]),
  group("outbound_icp", "Outbound / ICP Outreach", "surfaces", [
    metric({ id: "outbound.icp.sent", label: "Sent", family: "outbound_icp", area: "surfaces", surface: "email", description: "Outbound emails sent.", sources: [src("instantly", "sent"), src("lemlist", "sent")] }),
    metric({ id: "outbound.icp.reply_rate", label: "Reply rate", family: "outbound_icp", area: "surfaces", surface: "email", description: "Replies divided by sent or delivered emails.", format: "percent", aggregation: "avg", calculationKind: "ratio", sources: [src("instantly", "reply_rate"), src("instantly", "replies", "input")] }),
    metric({ id: "outbound.icp.positive_reply", label: "Positive reply", family: "outbound_icp", area: "surfaces", surface: "email", description: "Positive replies after sentiment or manual qualification.", format: "percent", aggregation: "avg", status: "planned", sources: [src("instantly", "positive_replies")] }),
    metric({ id: "outbound.icp.meetings_booked", label: "Meetings booked", family: "outbound_icp", area: "surfaces", surface: "email", description: "Meetings generated by outbound sequences.", status: "requires_mapping", sources: [src("instantly", "meetings_booked"), src("ghl", "appointments", "stage")] }),
    metric({ id: "outbound.icp.bounce_rate", label: "Bounce rate", family: "outbound_icp", area: "surfaces", surface: "email", description: "Bounced emails divided by sent emails.", format: "percent", aggregation: "avg", status: "planned", sources: [src("instantly", "bounce_rate")] }),
    metric({ id: "outbound.icp.open_rate_mpp", label: "Open rate with MPP warning", family: "outbound_icp", area: "surfaces", surface: "email", description: "Open rate flagged as unreliable when Apple MPP can inflate opens.", format: "percent", aggregation: "avg", sources: [src("instantly", "open_rate")] }),
    metric({ id: "outbound.icp.opt_out", label: "Opt-out", family: "outbound_icp", area: "surfaces", surface: "email", description: "Opt-out or unsubscribe rate.", format: "percent", aggregation: "avg", status: "planned", sources: [src("instantly", "opt_out_rate")] }),
    metric({ id: "outbound.icp.spam_complaint", label: "Spam complaint", family: "outbound_icp", area: "surfaces", surface: "email", description: "Spam complaint rate.", format: "percent", aggregation: "avg", status: "planned", sources: [src("instantly", "spam_complaint_rate")] }),
    metric({ id: "outbound.icp.sequence_funnel", label: "Sequence funnel", family: "outbound_icp", area: "surfaces", surface: "email", description: "Sent to opened/replied/meeting funnel by sequence.", calculationKind: "stage_rollup", requiredDimensions: ["sequence", "stage"], sources: [src("instantly", "sequence_step", "stage", { dimension: "sequence" })] }),
    metric({ id: "outbound.icp.reply_by_step", label: "Reply by step", family: "outbound_icp", area: "surfaces", surface: "email", description: "Replies grouped by sequence step.", requiredDimensions: ["step"], sources: [src("instantly", "replies", "primary", { dimension: "step" })] }),
    metric({ id: "outbound.icp.ab_compare", label: "A/B compare", family: "outbound_icp", area: "surfaces", surface: "email", description: "Outbound variant comparison.", requiredDimensions: ["variant"], status: "planned", sources: [src("instantly", "reply_rate", "primary", { dimension: "variant" })] }),
    metric({ id: "outbound.icp.deliverability_health", label: "Deliverability health", family: "outbound_icp", area: "surfaces", surface: "email", description: "Mailbox and DNS deliverability status.", format: "score", aggregation: "latest", status: "planned", sources: [src("deliverability", "health_score")] }),
  ]),
  group("partnerships", "Outbound / Partnerships", "surfaces", [
    metric({ id: "outbound.partnerships.invested", label: "Invested", family: "partnerships", area: "surfaces", surface: "partnerships", description: "Creator or partnership investment.", format: "currency", sources: [src("yalc", "invested", "cost"), src("creators", "payout", "cost")] }),
    metric({ id: "outbound.partnerships.cpa_real", label: "CPA real", family: "partnerships", area: "surfaces", surface: "partnerships", description: "Real CPA based on verified downstream conversion.", format: "currency", aggregation: "computed", calculationKind: "ratio", status: "requires_mapping", sources: [src("yalc", "invested", "cost"), src("metric_stage_rollups", "customer", "stage")] }),
    metric({ id: "outbound.partnerships.generated_value", label: "Generated value", family: "partnerships", area: "surfaces", surface: "partnerships", description: "Attributed value or revenue from partnerships.", format: "currency", calculationKind: "attribution", status: "requires_mapping", sources: [src("metric_attribution_results", "attributed_revenue", "revenue")] }),
    metric({ id: "outbound.partnerships.roi", label: "ROI", family: "partnerships", area: "surfaces", surface: "partnerships", description: "Generated value divided by partnership investment.", format: "ratio", aggregation: "computed", calculationKind: "ratio", status: "requires_mapping", sources: [src("metric_kpi_values", "outbound.partnerships.generated_value", "revenue"), src("metric_kpi_values", "outbound.partnerships.invested", "cost")] }),
    metric({ id: "outbound.partnerships.clicks", label: "Clicks", family: "partnerships", area: "surfaces", surface: "partnerships", description: "Creator or partner link clicks.", sources: [src("yalc", "clicks"), src("creators", "clicks")] }),
    metric({ id: "outbound.partnerships.signups", label: "Signups", family: "partnerships", area: "surfaces", surface: "partnerships", description: "Signups generated by partnerships.", sources: [src("yalc", "signups"), src("ga4", "signups", "input", { channel: "partnerships" })] }),
    metric({ id: "outbound.partnerships.kyc_approved", label: "KYC approved", family: "partnerships", area: "surfaces", surface: "partnerships", description: "KYC approvals from partnership traffic.", status: "requires_mapping", sources: [src("yalc", "kyc_approved"), src("koibox", "kyc_approved", "stage")] }),
    metric({ id: "outbound.partnerships.first_transaction", label: "First transaction", family: "partnerships", area: "surfaces", surface: "partnerships", description: "First funded transaction or equivalent downstream activation.", status: "requires_mapping", sources: [src("yalc", "first_transaction"), src("stripe", "first_payment", "stage")] }),
    metric({ id: "outbound.partnerships.creator_leaderboard", label: "Creator leaderboard", family: "partnerships", area: "surfaces", surface: "partnerships", description: "Creator performance ranked by configured outcome.", requiredDimensions: ["creator"], sources: [src("yalc", "clicks", "primary", { dimension: "creator" })] }),
    metric({ id: "outbound.partnerships.cpa_vs_break_even", label: "CPA vs break-even", family: "partnerships", area: "surfaces", surface: "partnerships", description: "CPA compared with configured break-even economics.", format: "currency", aggregation: "computed", calculationKind: "derived", status: "requires_mapping", sources: [src("yalc", "invested"), src("metric_definitions", "break_even_cpa", "input")] }),
    metric({ id: "outbound.partnerships.renew_watch_cut", label: "Renew / watch / cut", family: "partnerships", area: "surfaces", surface: "partnerships", description: "Decision panel derived from creator ROI and quality.", format: "text", aggregation: "latest", calculationKind: "derived", status: "requires_mapping", sources: [src("metric_signals", "partnership_decision")] }),
  ]),
  group("channels", "Channels", "channels", [
    metric({ id: "channels.attribution_model", label: "Attribution model selector", family: "channels", area: "channels", description: "Available attribution models for channel contribution.", format: "text", aggregation: "latest", calculationKind: "attribution", status: "requires_mapping", sources: [src("metric_attribution_results", "model")] }),
    metric({ id: "channels.mini_funnel", label: "Mini funnel", family: "channels", area: "channels", description: "Compact stage rollup by selected channel model.", calculationKind: "stage_rollup", status: "requires_mapping", sources: [src("metric_stage_rollups", undefined, "stage")] }),
    metric({ id: "channels.stage_matrix", label: "Channel x stage matrix", family: "channels", area: "channels", description: "Counts and rates by acquisition channel and business stage.", calculationKind: "attribution", status: "requires_mapping", requiredDimensions: ["channel", "stage"], sources: [src("metric_stage_rollups", undefined, "stage", { dimension: "channel" })] }),
    metric({ id: "channels.contribution_table", label: "Contribution table", family: "channels", area: "channels", description: "Attributed leads, pipeline, revenue and cost by channel.", format: "currency", calculationKind: "attribution", status: "requires_mapping", requiredDimensions: ["channel"], sources: [src("metric_attribution_results", "attributed_revenue", "primary", { dimension: "channel" })] }),
    metric({ id: "channels.model_comparison", label: "Model comparison", family: "channels", area: "channels", description: "Comparison between available attribution models.", calculationKind: "attribution", status: "requires_mapping", requiredDimensions: ["model"], sources: [src("metric_attribution_results", undefined, "primary", { dimension: "model" })] }),
    metric({ id: "channels.journeys", label: "Journeys multi-touch", family: "channels", area: "channels", description: "Top multi-touch paths and journey lengths.", calculationKind: "event", status: "planned", requiredDimensions: ["journey"], sources: [src("metric_stage_events", "touchpoint", "stage")] }),
    metric({ id: "channels.signals_bridge", label: "Attribution signals bridge", family: "channels", area: "channels", description: "Future Intelligence signals tied to attribution changes.", aggregation: "latest", calculationKind: "derived", status: "planned", sources: [src("metric_signals", "attribution")] }),
  ]),
  group("conversion", "Conversion", "conversion", [
    metric({ id: "conversion.end_to_end_funnel", label: "End-to-end funnel", family: "conversion", area: "conversion", description: "Full business funnel from traffic to revenue.", calculationKind: "stage_rollup", status: "requires_mapping", requiredDimensions: ["stage"], sources: [src("metric_stage_rollups", undefined, "stage", { dimension: "stage" })] }),
    metric({ id: "conversion.stage_rates", label: "Stage-to-stage rates", family: "conversion", area: "conversion", description: "Conversion rates between adjacent stages.", format: "percent", aggregation: "computed", calculationKind: "ratio", status: "requires_mapping", requiredDimensions: ["stage"], sources: [src("metric_stage_rollups", undefined, "stage")] }),
    metric({ id: "conversion.by_channel_matrix", label: "Conversion by channel matrix", family: "conversion", area: "conversion", description: "Stage conversion rates grouped by channel.", format: "percent", aggregation: "computed", calculationKind: "attribution", status: "requires_mapping", requiredDimensions: ["channel", "stage"], sources: [src("metric_stage_rollups", undefined, "stage", { dimension: "channel" })] }),
    metric({ id: "conversion.velocity", label: "Velocity / time to convert", family: "conversion", area: "conversion", description: "Time distribution between stages.", format: "duration", aggregation: "avg", calculationKind: "event", status: "requires_mapping", requiredDimensions: ["stage"], sources: [src("metric_stage_events", "duration_between_stages")] }),
    metric({ id: "conversion.leak_panel", label: "Leak panel", family: "conversion", area: "conversion", description: "Largest funnel losses and possible causes.", format: "text", aggregation: "latest", calculationKind: "derived", status: "requires_mapping", sources: [src("metric_kpi_values", "conversion.stage_rates"), src("metric_signals", "conversion_leak", "quality")] }),
    metric({ id: "conversion.signals_bridge", label: "Conversion signals bridge", family: "conversion", area: "conversion", description: "Future Intelligence signals tied to conversion changes.", aggregation: "latest", calculationKind: "derived", status: "planned", sources: [src("metric_signals", "conversion")] }),
  ]),
  group("trends", "Trends", "trends", [
    metric({ id: "trends.north_star_hero", label: "North Star hero trend", family: "trends", area: "trends", description: "North Star time series for the selected grain.", calculationKind: "derived", status: "requires_mapping", sources: [src("metric_kpi_values", "overview.north_star")] }),
    metric({ id: "trends.kpi_small_multiples", label: "KPI small multiples", family: "trends", area: "trends", description: "Small multiple trends for selected KPI definitions.", calculationKind: "derived", status: "requires_mapping", requiredDimensions: ["definition_id"], sources: [src("metric_kpi_values", undefined, "primary", { dimension: "definition_id" })] }),
    metric({ id: "trends.granularity", label: "Day / week / month granularity", family: "trends", area: "trends", description: "Supported trend grain selector.", format: "text", aggregation: "latest", calculationKind: "derived", sources: [src("metric_kpi_values", "grain")] }),
    metric({ id: "trends.compare_previous", label: "Compare previous", family: "trends", area: "trends", description: "Delta versus previous equivalent period.", format: "percent", aggregation: "computed", calculationKind: "derived", sources: [src("metric_kpi_values", "delta_pct")] }),
    metric({ id: "trends.compare_year", label: "Compare year", family: "trends", area: "trends", description: "Delta versus same period last year when available.", format: "percent", aggregation: "computed", calculationKind: "derived", status: "planned", sources: [src("metric_kpi_values", "year_delta_pct")] }),
    metric({ id: "trends.compare_target", label: "Compare target", family: "trends", area: "trends", description: "Progress against configured target.", format: "percent", aggregation: "computed", calculationKind: "ratio", status: "requires_mapping", sources: [src("metric_kpi_values", "value"), src("metric_definitions", "target", "input")] }),
    metric({ id: "trends.annotations", label: "Annotations / hitos", family: "trends", area: "trends", description: "Manual or system markers displayed on trend charts.", format: "text", aggregation: "latest", calculationKind: "manual", sources: [src("metric_annotations", undefined)] }),
    metric({ id: "trends.signals_bridge", label: "Trend signals bridge", family: "trends", area: "trends", description: "Future Intelligence signals tied to trend movements.", aggregation: "latest", calculationKind: "derived", status: "planned", sources: [src("metric_signals", "trend")] }),
  ]),
];
